### ISSUE TITLE
Microsoft.Azure.AppConfiguration.AspNetCore does not support User-Assigned Managed Identities

### ISSUE THREAD

**Issue by kuhsaft** [Azure/AppConfiguration#165]
When using a user-assigned managed identity with a Contributer role assigned to the resource the following error occurs:

```
Unhandled Exception: System.UnauthorizedAccessException: The specified user 'REDACTED' does not have the permissions required to access the configuration store.   at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.ManagedIdentityConnector.GetConnectionString(Uri endpoint, Permissions permissions, RequestOptions options, CancellationToken cancellationToken)
   at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.AzconfigClientFactory.CreateClient(Uri endpoint, AzconfigClientFactoryOptions options, CancellationToken cancellationToken)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationOptions.ConnectWithManagedIdentity(String endpoint)
   at Honeywell.SPS.CAIDC.MS.APIGateway.Program.<>c__DisplayClass1_0.<BuildWebHost>b__3(AzureAppConfigurationOptions options) in C:\Users\h361992\Projects\CPPRMicroservices\caidc_ms_apigateway\CAIDC_MS_APIGateway\Program.cs:line 61
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.<>c__DisplayClass2_0.<.ctor>b__0()
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Honeywell.SPS.CAIDC.MS.APIGateway.Program.Main(String[] args)
```

I am using AAD Pod Identity to add the managed identity to my AKS deployment.

Upon further digging it appears that the library is using `Microsoft.Azure.Services.AppAuthentication=1.0.3.0` which does not support user-assigned managed identities.

Is it possible to have an updated version with `Microsoft.Azure.Services.AppAuthentication=1.3.1` that supports user-assigned managed identities?

**Comment by zhenlan** [comment]
@kuhsaft thanks for reporting the issue. We are making changes in how we support managed identity. Yes, we will add the support of the user-assigned managed identity as part of the change.

**Comment by zhenlan** [comment]
hI @kuhsaft, with the release of v3 config provider, the user-assigned managed identity is now supported. Please check out the [release notes](https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md#300-preview-010550001-251---november-22-2019). You can use `ManagedIdentityCredential` with `clientId`.
