### ISSUE TITLE
[MSI] System.UnauthorizedAccessException: The specified user '<guid>' does not have the permissions required to access the configuration store.

### ISSUE THREAD

**Issue by BenjaBobs** [Azure/AppConfiguration#185]
As the title suggests, my App Service is getting an unauthorized access exception when trying to connect with MSI to my AAC.

The rest of the stack trace:
```
System.UnauthorizedAccessException: The specified user '<guid>' does not have the permissions required to access the configuration store.
   at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.ManagedIdentityConnector.GetConnectionString(Uri endpoint, Permissions permissions, RequestOptions options, CancellationToken cancellationToken)
   at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.ManagedIdentityConnector.GetConnectionString(Uri endpoint, Permissions permissions, CancellationToken cancellationToken)
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationOptions.ConnectWithManagedIdentity(String endpoint)
   at API.Program.&lt;&gt;c__DisplayClass1_0.&lt;CreateWebHostBuilder&gt;b__3(AzureAppConfigurationOptions options) in d:\a\1\s\API\Program.cs:line 27
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.&lt;&gt;c__DisplayClass2_0.&lt;.ctor&gt;b__0()
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException&amp; hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
```

By looking through the resources I found that I'm supposed to give the app service the `Contributor` role, so I did that, waited a few minutes and restarted the app service.

![image](https://user-images.githubusercontent.com/8708965/68460283-ba30ac00-0207-11ea-9c26-a1a32130f71f.png)

However I'm still getting unauthorized exceptions.

My app services uses the following config
```xml
//...
<TargetFramework>netcoreapp3.0</TargetFramework>
//...
<PackageReference Include="Microsoft.Extensions.Configuration" Version="3.0.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="3.0.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="3.0.0" />
<PackageReference Include="System.Configuration.ConfigurationManager" Version="4.5.0" />
<PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="2.1.0-preview-010380001-1099" />
```

It works properly when I run the app locally.
I can see in the IAM that I have the `Owner` role.

Any ideas on what I can do to fix this?

**Comment by BenjaBobs** [comment]
The issue seems to have resolved itself. About 40 minutes after granting the `Contributor` role the app service is now no longer getting the `UnauthorizedAccessException`.
