### ISSUE TITLE
Spring Boot app takes too long to start

### ISSUE THREAD

**Issue by ronak-viroja** [Azure/AppConfiguration#306]
Hi,

I've created a demo app using azure key-vault and Azure app-configuration. The app boot-up time is very high like 4-5 minutes. 

1) If I connect to only Azure app-configuration, the app works like charm. boots up within a minute.
2) If I connect to only Azure key-vault, the app works just fine again. boots up within a minute.

But when I try to connect to both of these, the app boot up time spikes up.

Also, when connected to both the key-vault and the app-configuration, it again takes 4-5 minutes to update the changed key every time from app-configuration.

Below is my pom.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.5.RELEASE</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo2</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo2</name>
	<description>Demo project for Spring Boot</description>

	<properties>
		<java.version>1.8</java.version>
		<azure.version>2.2.0</azure.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.microsoft.azure</groupId>
			<artifactId>spring-cloud-azure-appconfiguration-config-web</artifactId>
			<version>1.2.2</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.microsoft.azure</groupId>
				<artifactId>azure-spring-boot-bom</artifactId>
				<version>${azure.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

```

**Comment by ronak-viroja** [comment]
I also tried to add the app-configuration to our existing application which is using key-vault. In this case the app boot up is taking time about 10 minutes (otherwise 2-3 minutes) with the below logs flooded.

`2020-04-01 14:47:27.996 [pool-906-thread-1]  INFO c.m.a.a.AuthenticationAuthority --- : [Correlation ID: ppppppppp-pppp-pppp-pppp-pppppppppp] Instance discovery was successful`

**Comment by mrm9084** [comment]
@ronak-viroja Thanks for reporting the issue. I will start looking into it, I am not familiar with the key vault library mentioned. May I suggest you look at https://docs.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-spring-boot. App Configuration supports key vault references and if the client is configured to do so it will load Key Vault secrets.

**Comment by ronak-viroja** [comment]
Thanks @mrm9084 for the quick response. 
I tried key-vault-reference from app-configuration by following the documentation and below is my current set-up.

1. I've added key-vault access to app-configuration following [this documentation](https://docs.microsoft.com/en-gb/azure/key-vault/managed-identity) from Azure portal.
2. I've /resources/META-INF/spring.factories and these 3 env variables set (i) AZURE_CLIENT_ID (ii) AZURE_CLIENT_SECRET (iii) AZURE_TENANT_ID
3. As per the initial set-up, I have /resource/bootstrap.yaml having app-config connection-string

But I'm getting this exception.

`java.lang.IllegalArgumentException: More than 1 Conncetion method was set for connecting to App Configuration.
	at com.microsoft.azure.spring.cloud.config.stores.ClientStore.buildClient(ClientStore.java:65) ~[spring-cloud-azure-appconfiguration-config-1.2.2.jar:1.2.2]
	at com.microsoft.azure.spring.cloud.config.stores.ClientStore.listSettings(ClientStore.java:121) ~[spring-cloud-azure-appconfiguration-config-1.2.2.jar:1.2.2]
	at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySource.initProperties(AppConfigurationPropertySource.java:126) ~[spring-cloud-azure-appconfiguration-config-1.2.2.jar:1.2.2]
	at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySourceLocator.create(AppConfigurationPropertySourceLocator.java:206) ~[spring-cloud-azure-appconfiguration-config-1.2.2.jar:1.2.2]
	at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySourceLocator.addPropertySource(AppConfigurationPropertySourceLocator.java:139) ~[spring-cloud-azure-appconfiguration-config-1.2.2.jar:1.2.2]
	at com.microsoft.azure.spring.cloud.config.AppConfigurationPropertySourceLocator.locate(AppConfigurationPropertySourceLocator.java:92) ~[spring-cloud-azure-appconfiguration-config-1.2.2.jar:1.2.2]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:98) ~[spring-cloud-context-2.2.0.RELEASE.jar:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at com.example.demo2.Demo2Application.main(Demo2Application.java:17) [classes/:na]`


**Also, since our existing application is using key-vault, I'd really appreciate if you can provide some inputs on why the app boot-up is taking so long while connecting to both key-vault and configuration from my spring boot application since our existing application is already using key-vault.**

**Comment by mrm9084** [comment]
@ronak-viroja It looks like the error is coming from the library not knowing which connection method to use. It looks like that document could use some rework. An up to date sample is here https://github.com/microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/azure-appconfiguration-conversion-sample-initial.. With your Service Principal set up it you should also use it to connect to app configuration with the link explains, or just have `AzureCredentials` return  null for the `getAppConfigCredential` which will allow you to continue using the connection string.

As for key-vault, I am looking into what is causing that issue.

**Comment by saragluna** [comment]
@ronak-viroja 

Are you trying to connect the key vault via MSI or simply service principal? I've created a sample project with both KeyVault/App Configuration upgraded to our latest version and it starts within several seconds.

You could check the sample project here  https://github.com/saragluna/demo-appconfiguration-kv.

**Comment by ronak-viroja** [comment]
@saragluna 
Thanks for sample project. I tried cloning and running the application and worked just fine. Then I tried with our org's key-vault credentials and app-configuration connections-string and it loads all the keys from key-vault is what taking so much time. This would be fine upon app start-up as it's the first time load but this happens upon every refresh of the app-configuration values (only if the values are updated in app-config). Wondering why the key-vault values are being re-fetched if the app-config is refreshing.

**1. If no config has updated in app-config, below are the logs upon refreshing app-config from app.**

`2020-04-09 12:06:30.259  INFO 23977 --- [onPool-worker-4] c.a.d.a.ConfigurationAsyncClient         : Listing ConfigurationSetting revisions - SettingSelector(keyFilter=/application/*, labelFilter=*, acceptDateTime=null, fields=ALL_FIELDS)
2020-04-09 12:06:30.597  INFO 23977 --- [ctor-http-nio-3] c.a.d.a.ConfigurationAsyncClient         : Listed ConfigurationSetting revisions - SettingSelector(keyFilter=/application/*, labelFilter=*, acceptDateTime=null, fields=ALL_FIELDS)
2020-04-09 12:06:30.598  INFO 23977 --- [onPool-worker-4] c.a.d.a.ConfigurationAsyncClient         : Listing ConfigurationSetting revisions - SettingSelector(keyFilter=.appconfig*, labelFilter=*, acceptDateTime=null, fields=ALL_FIELDS)
2020-04-09 12:06:30.931  INFO 23977 --- [ctor-http-nio-3] c.a.d.a.ConfigurationAsyncClient         : Listed ConfigurationSetting revisions - SettingSelector(keyFilter=.appconfig*, labelFilter=*, acceptDateTime=null, fields=ALL_FIELDS)`

**2. If any of the config values are updated in app-configuration, below are the logs upon refreshing app-config form application.**

`2020-04-09 12:13:00.243  INFO 23977 --- [nPool-worker-13] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - test-key1
2020-04-09 12:13:04.567  INFO 23977 --- [ctor-http-nio-5] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - test-key1
2020-04-09 12:13:04.567  INFO 23977 --- [nPool-worker-13] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - test-key1
2020-04-09 12:13:05.321  INFO 23977 --- [ctor-http-nio-5] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - test-key1`

This is for just 1 key. It happens for every key. Also, please note that it tries to retrieve twice for each key here.

**After all the key are fetched it again fetched all the keys with below logs followed.** 

`2020-04-09 12:14:56.814  INFO 23977 --- [ctor-http-nio-5] c.a.s.k.secrets.SecretAsyncClient        : Retrieving the next secrets page - Page <key-vault-url-with-skip-token>
2020-04-09 12:14:56.814  INFO 23977 --- [nPool-worker-13] c.a.s.k.secrets.SecretAsyncClient        : Retrieving the next secrets page - Page <key-vault-url-with-skip-token>
2020-04-09 12:14:57.666  INFO 23977 --- [ctor-http-nio-5] c.a.s.k.secrets.SecretAsyncClient        : Retrieved the next secrets page - Page <key-vault-url-with-skip-token>
2020-04-09 12:14:57.667  INFO 23977 --- [ctor-http-nio-5] c.a.s.k.secrets.SecretAsyncClient        : Retrieving the next secrets page - Page <key-vault-url-with-skip-token>
2020-04-09 12:14:57.667  INFO 23977 --- [nPool-worker-13] c.a.s.k.secrets.SecretAsyncClient        : Retrieving the next secrets page - Page <key-vault-url-with-skip-token>
2020-04-09 12:14:58.439  INFO 23977 --- [ctor-http-nio-5] c.a.s.k.secrets.SecretAsyncClient        : Retrieved the next secrets page - Page <key-vault-url-with-skip-token>
2020-04-09 12:14:58.447  INFO 23977 --- [nPool-worker-13] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - test-key1
2020-04-09 12:14:59.152  INFO 23977 --- [ctor-http-nio-5] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - test-key1
2020-04-09 12:14:59.152  INFO 23977 --- [nPool-worker-13] c.a.s.k.secrets.SecretAsyncClient        : Retrieving secret - test-key1
2020-04-09 12:14:59.832  INFO 23977 --- [ctor-http-nio-5] c.a.s.k.secrets.SecretAsyncClient        : Retrieved secret - test-key1`

So, in total if any config is updated in app-config, all the key-vault values are fetched, 4 times in total for every refresh. Since we have 70+ keys in key-vault it takes a lot of time on refreshing app-configuration every time.

**Comment by saragluna** [comment]
@ronak-viroja  Thanks for the analysis. 

We have a property `azure.keyvault.secret.keys` to set the secrets you want to load from the key vault. You could find more details here https://github.com/microsoft/azure-spring-boot/tree/master/azure-spring-boot-starters/azure-keyvault-secrets-spring-boot-starter.

**Comment by ronak-viroja** [comment]
@saragluna 

I _do_ want to load _all the keys_ from the key-vault _but only_ at the start of the application.

I've set this property in my application `spring.cloud.azure.appconfiguration.watch.delay=60s` to refresh my app config values at every 60 seconds. So every time it tries to refresh app config properties, it fetches all the keys from key-vault, too. That is not expected, right?

**Comment by mrm9084** [comment]
@ronak-viroja What version of the library are you using. A full refresh of your configurations should not be happening when the cache expires. When the cache expires it should be just verifying that nothing has changes, which for most of the time should be true. There was a bug fixed in the latest version that saw some setups refresh every single refresh period. You may want to update to the latest version 1.2.3 to make sure this isn't happening.

**Comment by ronak-viroja** [comment]
@mrm9084 I'm using the version 1.2.3 for the app-configuration.
**spring-boot-starter-parent** : 2.2.5.RELEASE
**azure-keyvault-secrets-spring-boot-starter** : 2.2.4
**spring-cloud-azure-appconfiguration-config-web** : 1.2.3

**Comment by ronak-viroja** [comment]
@saragluna 
Using the sample project (https://github.com/saragluna/demo-appconfiguration-kv) you've created I'm able to reproduce this issue following the below steps.

1. start the application and hit http://localhost:8080
2. wait for a minute
3. Update the value of the  **config. messages** property in app configuration from azure portal.
4. Hit http://localhost:8080 again and the application will refresh the app configuration.
5. While refreshing, I am able to monitor the logs and it fetches the key-vault value **azure.cosmosdb.key** several time, 8 times to be exact.

**Comment by ronak-viroja** [comment]
@mrm9084 @saragluna Were able to reproduce the issue? any solution around this?

**Comment by zhenlan** [comment]
@mrm9084 @saragluna any updates?

**Comment by mrm9084** [comment]
@ronak-viroja I have used the example as stated, I see only 4 loads from key vault on a refresh, which is still an issue. So there are two things here. 

1. @saragluna when using the azure-keyvault-secrets-spring-boot-starter there is no way to only load keys from key vault only on startup. App Configuration reloads configurations through Springs Refresh functionality, which re-builds all Property Sources.

2. Also, @saragluna, I am not familiar with the given key vault library, but given the configurations in the example and following the instructions on github for the project I am unable to get any key vault secrets to load if I remove the use of App Configuration.

@ronak-viroja The best thing I think you could do is stop using azure-keyvault-secrets-spring-boot-starter and switch to Key Vault References in App Configuration.  See instructions here: https://docs.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-spring-boot. You can use the Service Principal you already have instead of making a new one.

This will solve the issue of multiple pulls from key vault, but the will still be re-pulled whenever App Configuration triggers a refresh.

**Comment by mrm9084** [comment]
@ronak-viroja and @saragluna I will be closing this issue. It seems to have diverged into 3 different items which we will track with the new issues I created above. I created the issues in the project repos for azure-spring-boot and spring-cloud-azure.
