### ISSUE TITLE
"Cannot wait on monitors on this runtime." on blazor wasm

### ISSUE THREAD

**Issue by tredition** [Azure/AppConfiguration#411]
On blazor wasm, Azure AppConfiguration can't be used. In Program.cs, I want to create a config service like this:

```
var builder = new ConfigurationBuilder();
builder.AddAzureAppConfiguration("Endpoint=xyz");
_config = builder.Build();
```

where _config is IConfigurationRoot. It works in blazor server and in all web api projects but not in blazor wasm. The following exception is thrown on browser console:

```
blazor.webassembly.js:1 System.PlatformNotSupportedException: Cannot wait on monitors on this runtime.
blazor.webassembly.js:1    at System.Threading.Monitor.ObjWait(Boolean exitContext, Int32 millisecondsTimeout, Object obj)
blazor.webassembly.js:1    at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout, Boolean exitContext)
blazor.webassembly.js:1    at System.Threading.Monitor.Wait(Object obj, Int32 millisecondsTimeout)
blazor.webassembly.js:1    at System.Threading.ManualResetEventSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
blazor.webassembly.js:1    at System.Threading.Tasks.Task.SpinThenBlockingWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
blazor.webassembly.js:1    at System.Threading.Tasks.Task.InternalWaitCore(Int32 millisecondsTimeout, CancellationToken cancellationToken)
blazor.webassembly.js:1    at System.Threading.Tasks.Task.InternalWait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
blazor.webassembly.js:1    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.Load()
blazor.webassembly.js:1    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
blazor.webassembly.js:1    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
blazor.webassembly.js:1    at tredition.Services.ConfigurationService..ctor() in D:\Entwicklung\tredition\tredition5\Shared\Generic\Services\ConfigurationService.cs:line 13
blazor.webassembly.js:1    at treditionClient.Program.Main(String[] args) in D:\Entwicklung\tredition\tredition5\treditionClient\Program.cs:line 25
blazor.webassembly.js:1    at Microsoft.AspNetCore.Components.WebAssembly.Hosting.EntrypointInvoker.InvokeEntrypoint(String assemblyName, String[] args)
```

**Comment by zhenlan** [comment]
Blazor support is tracked in #170
