### ISSUE TITLE
System.Configuration.ConfigurationErrorsException: The configBuilder 'MyConfigStore' failed while processing the configuration section 'appSettings'.: Error in Configuration Builder 'MyConfigStore'::GetAllValues()

### ISSUE THREAD

**Issue by SirElTomato** [Azure/AppConfiguration#462]
Hi, 

I am recieving the following message after configuring Azure App Configuration as per the [quickstart](https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-dotnet-app) in my application which already includes log4net. 

```
log4net:ERROR Exception while reading ConfigurationSettings. Check your .config file is well formed XML.
System.Configuration.ConfigurationErrorsException: The configBuilder 'MyConfigStore' failed while processing the configuration section 'appSettings'.: Error in Configuration Builder 'MyConfigStore'::GetAllValues() (C:\projects\xxx.exe.Config line 18) ---> System.Exception: Error in Configuration Builder 'MyConfigStore'::GetAllValues() ---> System.ArgumentException: Exception encountered while creating connection to Azure App Configuration store. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.TelemetryPolicy..ctor(String componentName, String componentVersion, String applicationId)
   at Azure.Core.Pipeline.HttpPipelineBuilder.CreateTelemetryPolicy(ClientOptions options)
   at Azure.Core.Pipeline.HttpPipelineBuilder.Build(ClientOptions options, HttpPipelinePolicy[] perCallPolicies, HttpPipelinePolicy[] perRetryPolicies, ResponseClassifier responseClassifier)
   at Azure.Data.AppConfiguration.ConfigurationClient.CreatePipeline(ConfigurationClientOptions options, HttpPipelinePolicy authenticationPolicy)
   at Azure.Data.AppConfiguration.ConfigurationClient..ctor(String connectionString, ConfigurationClientOptions options)
   at Microsoft.Configuration.ConfigurationBuilders.AzureAppConfigurationBuilder.LazyInitialize(String name, NameValueCollection config)
   --- End of inner exception stack trace ---
   at Microsoft.Configuration.ConfigurationBuilders.AzureAppConfigurationBuilder.LazyInitialize(String name, NameValueCollection config)
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.EnsureInitialized()
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.EnsureGreedyInitialized()
   --- End of inner exception stack trace ---
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.EnsureGreedyInitialized()
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.ProcessConfigurationSection(ConfigurationSection configSection)
   at System.Configuration.ConfigurationBuilderChain.ProcessConfigurationSection(ConfigurationSection configSection)
   --- End of inner exception stack trace ---
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at log4net.Util.SystemInfo.GetAppSetting(String key)
```

```
<configuration>
  <configSections>
    <section name="log4net" type="log4net.Config.Log4NetConfigurationSectionHandler, log4net" />
    <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    <section name="configBuilders" type="System.Configuration.ConfigurationBuildersSection, System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" restartOnExternalChanges="false" requirePermission="false" />
  </configSections>

    <configBuilders>
        <builders>
            <add name="MyConfigStore" mode="Greedy" connectionString="Endpoint=https://appconfig-nopermissions.azconfig.io;Id=xxxxx;Secret=xxxxx" type="Microsoft.Configuration.ConfigurationBuilders.AzureAppConfigurationBuilder, Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration" />
            <add name="Environment" mode="Greedy" type="Microsoft.Configuration.ConfigurationBuilders.EnvironmentConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Environment" />
        </builders>
    </configBuilders>
    
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.2" />
  </startup>
  <appSettings configBuilders="Environment,MyConfigStore">
    <add key="AppName" value="Console App Demo" />
  </appSettings>
</configuration>
```

The config file has a lot more in it, but I think I have included everything which is relevant. 

The error doesn't occur if I remove "configBuilders="Environment,MyConfigStore"" from the appSettings declaration. 

I can't provide a stacktrace because even though I have wrapped the code in Program.cs in a try/catch, no exception is caught. 

```
            try
            {
                string message = System.Configuration.ConfigurationManager.AppSettings["TestApp:Settings:Message"];

                Console.WriteLine(message);
                Console.ReadKey();

            }
            catch (Exception ex)
            {

                throw;
            }
```

Thanks

**Comment by zhenlan** [comment]
@SirElTomato from the other issue you opened (#461), looks like you may have the code working already. Please let us know if it's not the case.

BTW, you may accidentally expose the connection string of your App Configuration store in your question. I've updated your original post to remove it. You may consider rotating the connection string ASAP too.

**Comment by SirElTomato** [comment]
@zhenlan no I don't have this working. The other issue I opened was in a brand new project, this is when adding to an existing project and it looks like it might be clashing with Log4net? 

Thanks I know, I have since deleted the app service anyway

**Comment by zhenlan** [comment]
@SirElTomato not sure about Log4net. Does your project work if you remove the Log4net temporarily? Any other differences between this project and the new project you created?

**Comment by SirElTomato** [comment]
@zhenlan No I still get the same error when removing log4net from the config file.

**Comment by zhenlan** [comment]
@SirElTomato since the error you shared is originated from log4net, I assumed it would be a new error after you removed the log4net from your project? I cannot spot the issue from the information you shared. Can you please compare this project with the project that works for you and let us know what you find out?

**Comment by zhenlan** [comment]
@SirElTomato I suppose this is resolved. Closing.
