### ISSUE TITLE
Microsoft.Extensions.Configuration.AzureAppConfiguration.KeyVaultReferenceException: No key vault credential or secret resolver callback configured, and no matching secret client could be found.

### ISSUE THREAD

**Issue by kamlesh-nb** [Azure/AppConfiguration#581]
I am trying to use managed identity to access app configuration and key vault secrets can get the app config but not the secret from the key vault that app config key points to. The code is deployed as a docker container in Azure app Service, that uses System-assigned managed identity, which has been given the following roles.

**App Configuration Data Reader**
**Key Vault Secrets User**

```
Microsoft.Extensions.Configuration.AzureAppConfiguration.KeyVaultReferenceException: No key vault credential or secret resolver callback configured, and no matching secret client could be found.. ErrorCode:, Key: <key>, Label:, Etag:2jVYDJMXXIEuCfC2x6gHIQhuNfF, SecretIdentifier:https://<kv name>.vault.azure.net/secrets/<secrete>
2021-12-08T11:50:01.675365099Z  ---> System.UnauthorizedAccessException: No key vault credential or secret resolver callback configured, and no matching secret client could be found.
2021-12-08T11:50:01.677728202Z    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureKeyVault.AzureKeyVaultSecretProvider.GetSecretValue(Uri secretUri, String key, CancellationToken cancellationToken)
2021-12-08T11:50:01.677747502Z    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureKeyVault.AzureKeyVaultKeyValueAdapter.ProcessKeyValue(ConfigurationSetting setting, CancellationToken cancellationToken)
2021-12-08T11:50:01.677763802Z    --- End of inner exception stack trace ---
2021-12-08T11:50:01.677769002Z    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureKeyVault.AzureKeyVaultKeyValueAdapter.ProcessKeyValue(ConfigurationSetting setting, CancellationToken cancellationToken)
2021-12-08T11:50:01.677773302Z    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.ProcessAdapters(ConfigurationSetting setting, CancellationToken cancellationToken)
2021-12-08T11:50:01.677777502Z    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.SetData(IDictionary`2 data, Boolean ignoreFailures, CancellationToken cancellationToken)
2021-12-08T11:50:01.677781702Z    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.LoadAll(Boolean ignoreFailures)
2021-12-08T11:50:01.677785802Z    at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationProvider.Load()
2021-12-08T11:50:01.677789802Z    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
2021-12-08T11:50:01.677793602Z    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
2021-12-08T11:50:01.677797502Z    at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
2021-12-08T11:50:01.677801202Z    at Microsoft.Extensions.Hosting.HostBuilder.Build()
```

**Comment by zhenlan** [comment]
@kamlesh-nb in your code, did you call `ConfigureKeyVault` to let the config provider know which credential you want the provider to use to connect to your Key Vault? See examples in step 3 of the doc below.

https://docs.microsoft.com/en-us/azure/azure-app-configuration/use-key-vault-references-dotnet-core?tabs=core5x#update-your-code-to-use-a-key-vault-reference

**Comment by kamlesh-nb** [comment]
@zhenlan I have tried all the options, but it still didn't work in the Azure App Service, on local it works with user secrets having AAC Endpoint.

**Comment by zhenlan** [comment]
@kamlesh-nb hard to guess what went wrong. Could you please share your code?

**Comment by kamlesh-nb** [comment]
Following are the options that I tried;

a:

```
config.AddAzureAppConfiguration(options =>
              {
                var managedCred = new ManagedIdentityCredential();
                _ = !IsDevelopment() ?
                    
                    options.Connect(new Uri(settings["AppConfig:Endpoint"]), managedCred ) :

                    options.Connect(settings["AppConfig:Endpoint"])

              .ConfigureRefresh(refresh =>
                  {
                    refresh.Register("xTool:Settings:Sentinel", refreshAll: true)
                              .SetCacheExpiration(new TimeSpan(0, 5, 0));
                  }).ConfigureKeyVault(kv =>
                  {
                    kv.SetCredential(new ClientSecretCredential(settings["AppConfig:TenantId"], 
                            settings["AppConfig:ClientId"], settings["AppConfig:Secret"]));
                  });
              });
```

b.

 ```
.ConfigureAppConfiguration((hostingContext, config) =>
            {
              var settings = config.Build();
              
              if(hostingContext.HostingEnvironment.IsDevelopment()){ 
                config.AddAzureAppConfiguration(options =>
                {
                  options.Connect(settings["AppConfig:Endpoint"])
                  .ConfigureRefresh(refresh =>
                    {
                      refresh.Register("Settings:Sentinel", refreshAll: true)
                                .SetCacheExpiration(new TimeSpan(0, 5, 0));
                    }).ConfigureKeyVault(kv =>
                    {
                      kv.SetCredential(new DefaultAzureCredential());  
                    });
                });
              } else {
                var secretClient = new SecretClient(
                      new Uri($"https://{settings["AppConfig:KeyVaultName"]}.vault.azure.net/"),
                      new DefaultAzureCredential());
                config.AddAzureAppConfiguration(options => {
                  var managedCred = new ManagedIdentityCredential();
                  options.Connect(new Uri(settings["AppConfig:Endpoint"]), managedCred)
                  .ConfigureRefresh(refresh => {
                    refresh.Register("Settings:Sentinel", refreshAll: true)
                              .SetCacheExpiration(new TimeSpan(0, 5, 0));
                  });
                }).AddAzureKeyVault(secretClient, new KeyVaultSecretManager());
              }
            })
```

c.

```
.ConfigureAppConfiguration((hostingContext, config) =>
            {
              var settings = config.Build();
              var endPoint = hostingContext.HostingEnvironment.IsDevelopment() ? 
                              settings["AppConfig:Endpoint"] :
                              Environment.GetEnvironmentVariable("AppConfigEndpoint");
              config.AddAzureAppConfiguration(options =>
              {
                options.Connect(endPoint)
                         .ConfigureRefresh(refresh =>
                              {
                                refresh.Register("Settings:Sentinel", refreshAll: true)
                                         .SetCacheExpiration(new TimeSpan(0, 5, 0));
                              }).ConfigureKeyVault(kv =>
                              {
                                kv.SetCredential(new DefaultAzureCredential());
                              });
              });
```


Option C is working as I have added AAC Connection String in App Service Configuration. But I did not want to use it via App Service Configuration have AAC Connection String.

**Comment by zhenlan** [comment]
If option C works except it is using the connection string. You can update it to below to connect with managed identity:

```cs
.ConfigureAppConfiguration((hostingContext, config) =>
            {
              var settings = config.Build();
              var endPoint = settings["AppConfig:Endpoint"];
              config.AddAzureAppConfiguration(options =>
              {
                options.Connect(endPoint, new DefaultAzureCredential())
                       .ConfigureRefresh(refresh =>
                              {
                                refresh.Register("Settings:Sentinel", refreshAll: true)
                                         .SetCacheExpiration(new TimeSpan(0, 5, 0));
                              })
                       .ConfigureKeyVault(kv =>
                              {
                                kv.SetCredential(new DefaultAzureCredential());
                              });
              });

```

- Make sure `settings["AppConfig:Endpoint"]` is something like "https://\<yourstorename\>.azconfig.io"
- Make sure you grant your App Service managed identity `App Configuration Data Reader` role in App Configuration.

**Comment by kamlesh-nb** [comment]
@zhenlan I will give it a try, currently busy with the release, will update you once I try your suggestion.

**Comment by zhenlan** [comment]
@kamlesh-nb please let us know if you have an update. Closing for now.
