### ISSUE TITLE
TaskCanceledException at System.Reactive, .Net Framework

### ISSUE THREAD

**Issue by Iscgx** [Azure/AppConfiguration#70]
Hello all,

I'm facing some issue using the latest pre-release version of the .Net library (at the time of this writing 1.0.0-preview-0085200001). It appears to be specific to .Net Framework (using version 4.7.1) as I'm unable to reproduce it with the same code in .Net Core 2.1.

I'm using the [.Net Generic Host ](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2) instead of the ASP.NET Core Host (not sure if it is relevant). [Here's my code](https://gist.github.com/Iscgx/241b77f55f13f38e491b4c1f47503c34). 

I'm basically printing a single value taken from an AzureAppConfiguration service. If I enable the polling with the Watch method, after a few seconds I see the following exception:

```
System.Threading.Tasks.TaskCanceledException: 'A task was canceled.'
```
Stack trace:
```
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.ObservableSelector._.InnerObserver.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Concat`1._.OnError(Exception error)
   at System.Reactive.Linq.ObservableImpl.Delay`1.Base`1.L.DrainQueue(ICancelable cancel)
   at System.Reactive.Concurrency.Scheduler.<>c.<ScheduleLongRunning>b__73_0(Action`1 a, ICancelable c)
   at System.Reactive.Concurrency.DefaultScheduler.LongRunning.<>c__DisplayClass1_0`1.<ScheduleLongRunning>b__0(Object arg)
   at System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.<>c__DisplayClass7_0.<StartThread>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by dawwa** [comment]
Same here, we started getting this error this morning, and still happening.
Seems some service side issue?

Unhandled Exception: System.Net.Http.HttpRequestException: The operation was canceled. ---> **System.Threading.Tasks.TaskCanceledException: The operation was canceled.**
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.AppConfiguration.Azconfig.AzconfigHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.AppConfiguration.Azconfig.AzconfigMessageInvoker.SendAsync(Func`1 requester, CancellationToken cancellationToken)
   at Microsoft.Azure.AppConfiguration.Azconfig.AzconfigClient.GetCurrentKeyValue(IKeyValue keyValue, CancellationToken cancellationToken)
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ExceptionServicesImpl.cs:line 16
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Stubs.cs:line 16

**Comment by jimmyca15** [comment]
Hello @Iscgx and @dawwa. This is currently a known issue with our provider that we are seeking to address. The watch capability does not retry at an adequate level when presented with transient network errors. Unfortunately, this causes the polling to stop when an exception like this occurs. Currently, there is no work around, the entire configuration object would have to be **created again** to keep polling. We are looking to get a new version out soon that will prevent this from occurring. 

Also worth mentioning here is we do plan on reworking the polling mechanism a bit so that the polling does not occur "magically" under the hood with no control mechanism available in code. Rather, the trigger for refreshing will be accessible. This will allow everyone to refresh the configuration as they desire, whether per request, on a timer, or any desired criteria. We will of course provide integration points to make it easy to hook this up where possible.

**Comment by jimmyca15** [comment]
This should be fixed in our latest release. We updated the observable to not enter a detached state if there are transient network errors. 

Package: https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureAppConfiguration/1.0.0-preview-008920001-990

Release Notes: https://github.com/Azure/AppConfiguration/blob/master/releaseNotes/MicrosoftExtensionsConfigurationAzureAppConfiguration.md
