### ISSUE TITLE
Get "413 Request Entity Too Large" with ConfigurationClient.SetConfigurationSetting, but can't determine why

### ISSUE THREAD

**Issue by crushroll** [Azure/AppConfiguration#755]
I'm using the ConfigurationClient class with SetConfigurationSetting to store many key / value pair into Azure App Configuration.
All keys are just text with hyphens, e.g. a-b-c-d, no labels, and all values are JSON, and all key/value combinations are < 10kb. 
However, one key out of 30+ or so keys I'm storing, always failing with an exception and 413 error.
If I paste the JSON value into the key in the Azure Portal, it stores successfully.

There is nothing out of the ordinary, that I can tell, about the key or values. 
The key is similar to others. 
The value is JSON, and the size is approx. 6300 bytes, which is smaller than the largest of around 7400 bytes.

I have tried storing to a different key, still fails, so I assume it's the value that is triggering the problem.
I checked the value doesn't have special characters, JSON validity (which shouldn't really matter), I've tried to determine if specific values in the value trigger some issue in the request, but I have not been able to figure out the exact parameters that make it work or not, except that if the size of the value < 6023 bytes - that is the tipping point when the it doesn't throw an exception, and the key/value stores successfully.

I cannot determine why is fails, any help would be appreciated. Is there anything that is obviously it how key/values are stored, that I should be aware of, that might affect me?

Also, I cannot post the key/value here, as they contain internal information. I can work privately with someone from Microsoft if need be.

Sorry, forgot to add the exception here:

Exception: Azure.RequestFailedException: Service request failed.
Status: 413 (Request Entity Too Large)

Content:
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>openresty/1.21.4.1</center>
</body>
</html>

Headers:
Server: openresty/1.21.4.1
Date: Thu, 11 May 2023 02:52:39 GMT
Xonnection: REDACTED
Access-Control-Allow-Origin: *
Connection: Keep-Alive
Content-Type: text/html
Content-Length: 189

   at Azure.Data.AppConfiguration.ConfigurationClient.SetConfigurationSetting(ConfigurationSetting setting, Boolean onlyIfUnchanged, CancellationToken cancellationToken)
   at Azure.Data.AppConfiguration.ConfigurationClient.SetConfigurationSetting(String key, String value, String label, CancellationToken cancellationToken)

**Comment by crushroll** [comment]
Don't worry, I worked it out by putting verbose logging on. The quotes are converted to unicode \u0022 which make this payload exceed the 10kb limit.
