### ISSUE TITLE
Cannot authenticate with service principal

### ISSUE THREAD

**Issue by krenaut1** [Azure/AppConfiguration#783]
Is it possible to authenticate to app configuration using a service principal? In the error logs it looks like its trying to use managed identity.
I am using spring boot 3.1.1
I set environment variables in my pipeline as follows:
`AZURE_CLIENT_ID=#{msvc-keyvault-client-id}#`
`AZURE_TENANT_ID=#{msvc-keyvault-tenant-id}#`
`AZURE_CLIENT_SECRET=#{msvc-keyvault-client-secret}#`

My service principal only has role "App Configuration Data Reader" for the App Configuration service.
I am not using any secret references in my test configuration so key vault should not be involved.
I am using bootstrap.yml with these settings:
`spring:`
`  application:`
`    name: experiment`
`  cloud:`
`    azure:`
`      appconfiguration:`
`        stores[0]:`
`          endpoint: https://xxxxxxxxxxxxx.azconfig.io`
`          selects[0]:`
`            key-filter: /test/` 
`            label-filter: \0`
My relevant parts of my pom.xml
`		<dependency>`
`			<groupId>org.springframework.cloud</groupId>`
`			<artifactId>spring-cloud-starter-bootstrap</artifactId>`
`			<version>4.0.3</version>`
`		</dependency>`
`		<dependency>`
`			<groupId>com.azure.spring</groupId>`
`			<artifactId>azure-spring-cloud-appconfiguration-config-web</artifactId>`
`			<version>2.11.0</version>`
`		</dependency>`
`	</dependencies>`
`	<dependencyManagement>`
`	<dependencies>`
`		<dependency>`
`		<groupId>com.azure.spring</groupId>`
`		<artifactId>spring-cloud-azure-dependencies</artifactId>`
`		<version>5.3.0</version>`
`		<type>pom</type>`
`		<scope>import</scope>`
`		</dependency>`
`	</dependencies>`
`	</dependencyManagement>`
logs:
`2023-07-06T03:25:52.730-05:00 DEBUG 1 --- [           main] c.a.identity.ManagedIdentityCredential   : Azure Identity => Found the following environment variables: AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_CLIENT_SECRET
2023-07-06T03:25:55.031-05:00 DEBUG 1 --- [       Thread-2] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@1b0c644e6 pairs: {GET /metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fac-msvc-dev-eus-001.azconfig.io HTTP/1.1: null}{Metadata: true}{User-Agent: azsdk-java-azure-identity/1.9.1 (17.0.7; Linux; 5.15.0-1038-azure)}{Host: 169.254.169.254}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
2023-07-06T03:25:55.091-05:00 DEBUG 1 --- [       Thread-2] s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@56c8ec1a6 pairs: {null: HTTP/1.1 400 Bad Request}{content-type: application/json; charset=utf-8}{server: envoy}{date: Thu, 06 Jul 2023 08:25:54 GMT}{content-length: 68}{x-envoy-upstream-service-time: 44}
2023-07-06T03:25:55.093-05:00 ERROR 1 --- [       Thread-2] c.a.i.implementation.IdentityClient      : ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
2023-07-06T03:25:55.098-05:00 ERROR 1 --- [       Thread-2] c.a.identity.ManagedIdentityCredential   : Azure Identity => ERROR in getToken() call for scopes [https://ac-msvc-dev-eus-001.azconfig.io/.default]: Managed Identity authentication is not available.
2023-07-06T03:25:55.099-05:00 ERROR 1 --- [       Thread-2] c.a.c.implementation.AccessTokenCache    : {"az.sdk.message":"Failed to acquire a new access token.","exception":"Managed Identity authentication is not available."}

com.azure.identity.CredentialUnavailableException: Managed Identity authentication is not available.
        at com.azure.identity.implementation.IdentityClient.lambda$authenticateWithManagedIdentityConfidentialClient$21(IdentityClient.java:525) ~[azure-identity-1.9.1.jar:1.9.1]
        at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3783) ~[reactor-core-3.5.7.jar:3.5.7]
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.5.7.jar:3.5.7]
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondError(MonoFlatMap.java:241) ~[reactor-core-3.5.7.jar:3.5.7]
        at reactor.core.publisher.MonoFlatMap$FlatMapInner.onError(MonoFlatMap.java:315) ~[reactor-core-3.5.7.jar:3.5.7]
        at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:119) ~[reactor-core-3.5.7.jar:3.5.7]
        at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:71) ~[reactor-core-3.5.7.jar:3.5.7]
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: com.microsoft.aad.msal4j.MsalAzureSDKException: java.util.concurrent.ExecutionException: com.azure.identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
        at com.microsoft.aad.msal4j.AcquireTokenByAppProviderSupplier.fetchTokenUsingAppTokenProvider(AcquireTokenByAppProviderSupplier.java:79) ~[msal4j-1.13.8.jar:1.13.8]
        at com.microsoft.aad.msal4j.AcquireTokenByAppProviderSupplier.execute(AcquireTokenByAppProviderSupplier.java:56) ~[msal4j-1.13.8.jar:1.13.8]
        at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.acquireTokenByClientCredential(AcquireTokenByClientCredentialSupplier.java:78) ~[msal4j-1.13.8.jar:1.13.8]
        at com.microsoft.aad.msal4j.AcquireTokenByClientCredentialSupplier.execute(AcquireTokenByClientCredentialSupplier.java:49) ~[msal4j-1.13.8.jar:1.13.8]
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:69) ~[msal4j-1.13.8.jar:1.13.8]
        at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:18) ~[msal4j-1.13.8.jar:1.13.8]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[na:na]
        ... 1 common frames omitted
Caused by: java.util.concurrent.ExecutionException: com.azure.identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[na:na]
        at com.microsoft.aad.msal4j.AcquireTokenByAppProviderSupplier.fetchTokenUsingAppTokenProvider(AcquireTokenByAppProviderSupplier.java:76) ~[msal4j-1.13.8.jar:1.13.8]
        ... 7 common frames omitted
Caused by: com.azure.identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established.
        at com.azure.identity.implementation.IdentityClient.lambda$authenticateToIMDSEndpoint$57(IdentityClient.java:1139) ~[azure-identity-1.9.1.jar:1.9.1]
        at reactor.core.publisher.MonoCallable.call(MonoCallable.java:72) ~[reactor-core-3.5.7.jar:3.5.7]
        at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:174) ~[reactor-core-3.5.7.jar:3.5.7]
        at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[reactor-core-3.5.7.jar:3.5.7]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4480) ~[reactor-core-3.5.7.jar:3.5.7]
        at reactor.core.publisher.Mono.subscribeWith(Mono.java:4561) ~[reactor-core-3.5.7.jar:3.5.7]
        at reactor.core.publisher.Mono.toFuture(Mono.java:5073) ~[reactor-core-3.5.7.jar:3.5.7]
        at com.azure.identity.implementation.IdentityClientBase.lambda$getManagedIdentityConfidentialClient$3(IdentityClientBase.java:362) ~[azure-identity-1.9.1.jar:1.9.1]
        at com.microsoft.aad.msal4j.AcquireTokenByAppProviderSupplier.fetchTokenUsingAppTokenProvider(AcquireTokenByAppProviderSupplier.java:75) ~[msal4j-1.13.8.jar:1.13.8]
        ... 7 common frames omitted`

**Comment by zhenlan** [comment]
Hi @krenaut1, for Spring Boot 3 apps, you should use version 5.* App Configuration library. See more information:

https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-java-spring-app?tabs=spring-boot-3#connect-to-an-app-configuration-store

**Comment by krenaut1** [comment]
@zhenlan thank you so much!  One more hopefully easy question.  Now I am getting java.lang.IllegalArgumentException: KeyFilter must not contain asterisk(*).  What is the proper key filter syntax to select all the keys with the same prefix?

**Comment by krenaut1** [comment]
@zhenlan thank you so much! My app is working.

**Comment by krenaut1** [comment]
Closing issue.

**Comment by krenaut1** [comment]
Closing issue.
