### ISSUE TITLE
.NET Client - Required signing request header 'date' not found

### ISSUE THREAD

**Issue by Turochamp** [Azure/AppConfiguration#854]
Are using the .NET Client and gettings the error below and I can find no documentation on why it is happening? The REST Api documentation describes similar error messages though.

Is this a bug in the client or is it that my code needs to be adjusted?

**Error message:**
> Azure.RequestFailedException: Service request failed.
> Status: 401 (Unauthorized)
> 
> Headers:
> Date: Fri, 22 Dec 2023 18:30:25 GMT
> WWW-Authenticate: HMAC-SHA256 error="invalid_token", error_description="Required signing request header 'date' not found", Bearer
> x-ms-client-request-id: 2ac2962e-2fb7-433c-887f-c7b164c523f7
> x-ms-correlation-request-id: 32b017c5-86a1-4884-be99-39669390e6e5
> x-ms-request-id: 32b017c5-86a1-4884-be99-39669390e6e5
> Content-Length: 0
> 
>    at Azure.Core.PageableHelpers.PageableImplementation`1[[Azure.Data.AppConfiguration.ConfigurationSetting, Azure.Data.AppConfiguration, Version=1.3.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]].GetResponse(HttpMessage message)
>    at Azure.Core.PageableHelpers.PageableImplementation`1.<GetNextResponseAsync>d__20[[Azure.Data.AppConfiguration.ConfigurationSetting, Azure.Data.AppConfiguration, Version=1.3.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]].MoveNext()
>    at Azure.Core.PageableHelpers.PageableImplementation`1.<GetAsyncEnumerator>d__15[[Azure.Data.AppConfiguration.ConfigurationSetting, Azure.Data.AppConfiguration, Version=1.3.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]].MoveNext()
>    at Azure.Core.PageableHelpers.PageableImplementation`1.<GetAsyncEnumerator>d__15[[Azure.Data.AppConfiguration.ConfigurationSetting, Azure.Data.AppConfiguration, Version=1.3.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]].System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
>    at BlazorAdmin.Services.AppConfigurationService.List(SettingSelector selector) in C:\Src\eShopOnWeb\src\BlazorAdmin\Services\AppConfigurationService.cs:line 24
>    at BlazorAdmin.Services.AppConfigurationService.List(SettingSelector selector) in C:\Src\eShopOnWeb\src\BlazorAdmin\Services\AppConfigurationService.cs:line 24
>    at BlazorAdmin.Pages.ConfigurationSettingPage.List.OnAfterRenderAsync(Boolean firstRender) in C:\Src\eShopOnWeb\src\BlazorAdmin\Pages\ConfigurationSettingPage\List.razor.cs:line 27
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Code**
```
    public async Task<List<ConfigurationSetting>> List(BlazorShared.Models.SettingSelector selector = null)
    {
        var settings = new List<ConfigurationSetting>();
        var client = new ConfigurationClient(_connectionString);

        await foreach (var setting in client.GetConfigurationSettingsAsync(Map(selector)))
        {
            settings.Add(Map(setting));
        }
        return settings;
    }
```

**Comment by Turochamp** [comment]
Posted a new issue in the AppConfiguration-DotnetProvider repo.
https://github.com/Azure/AppConfiguration-DotnetProvider/issues/506
